services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: stylelint-fe
    ports:
      - '5001:8080'
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
